
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'Container': typeof import("../components/global/Container.vue")['default']
    'Section': typeof import("../components/global/Section.vue")['default']
    'AppFooter': typeof import("../components/app/Footer/Footer.vue")['default']
    'AppHeader': typeof import("../components/app/Header/Header.vue")['default']
    'AppHeaderHeaderDesktopLocale': typeof import("../components/app/Header/HeaderDesktop/HeaderDesktopLocale.vue")['default']
    'AppHeaderHeaderDesktop': typeof import("../components/app/Header/HeaderDesktop/index.vue")['default']
    'AppHeaderHeaderMenuLink': typeof import("../components/app/Header/HeaderMenuLink/index.vue")['default']
    'AppHeaderHeaderMobileBurger': typeof import("../components/app/Header/HeaderMobile/HeaderMobileBurger.vue")['default']
    'AppHeaderHeaderMobileLocale': typeof import("../components/app/Header/HeaderMobile/HeaderMobileLocale.vue")['default']
    'AppHeaderHeaderMobileMenu': typeof import("../components/app/Header/HeaderMobile/HeaderMobileMenu.vue")['default']
    'AppHeaderHeaderMobile': typeof import("../components/app/Header/HeaderMobile/index.vue")['default']
    'IconsIconDownloadAppStore': typeof import("../components/icons/IconDownloadAppStore.vue")['default']
    'IconsIconDownloadGooglePlay': typeof import("../components/icons/IconDownloadGooglePlay.vue")['default']
    'IconsIconDownloadMacOs': typeof import("../components/icons/IconDownloadMacOs.vue")['default']
    'IconsIconDownloadWindows': typeof import("../components/icons/IconDownloadWindows.vue")['default']
    'IconsIconEarth': typeof import("../components/icons/IconEarth.vue")['default']
    'IconsIconWrap': typeof import("../components/icons/IconWrap.vue")['default']
    'PagesMainBenefits': typeof import("../components/pages/main/Benefits.vue")['default']
    'PagesMainFaq': typeof import("../components/pages/main/Faq.vue")['default']
    'PagesMainFaqItem': typeof import("../components/pages/main/Faq/FaqItem.vue")['default']
    'PagesMainFcp': typeof import("../components/pages/main/Fcp.vue")['default']
    'PagesMainGlobalNetwork': typeof import("../components/pages/main/GlobalNetwork.vue")['default']
    'PagesMainGlobalNetworkCard': typeof import("../components/pages/main/GlobalNetwork/GlobalNetworkCard.vue")['default']
    'PagesMainNoLogs': typeof import("../components/pages/main/NoLogs.vue")['default']
    'PagesMainNoLogsCard': typeof import("../components/pages/main/NoLogs/NoLogsCard.vue")['default']
    'PagesMainServers': typeof import("../components/pages/main/Servers.vue")['default']
    'PagesMainServersCard': typeof import("../components/pages/main/Servers/ServersCard.vue")['default']
    'PagesMainSupport': typeof import("../components/pages/main/Support.vue")['default']
    'PagesMainSupportDonateCalc': typeof import("../components/pages/main/Support/DonateCalc.vue")['default']
    'SectionsBenefitsOfServers': typeof import("../components/sections/BenefitsOfServers.vue")['default']
    'SectionsBenefitsOfServersCard': typeof import("../components/sections/BenefitsOfServers/BenefitsOfServersCard.vue")['default']
    'SectionsConnectAndPrivate': typeof import("../components/sections/ConnectAndPrivate.vue")['default']
    'SectionsConnectAndPrivateCard': typeof import("../components/sections/ConnectAndPrivate/ConnectAndPrivateCard.vue")['default']
    'SectionsFirstContentfulPaint': typeof import("../components/sections/FirstContentfulPaint.vue")['default']
    'SectionsHowToSetUp': typeof import("../components/sections/HowToSetUp.vue")['default']
    'SectionsHowToSetUpCard': typeof import("../components/sections/HowToSetUp/SetUpCard.vue")['default']
    'SectionsPlatformsListPlatformItem': typeof import("../components/sections/PlatformsList/PlatformItem.vue")['default']
    'SectionsPlatformsList': typeof import("../components/sections/PlatformsList/PlatformsList.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtImg': typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-img")['default']
    'NuxtPicture': typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-picture")['default']
    'NuxtLinkLocale': typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
    'SwitchLocalePathLink': typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
    'SiteLink': typeof import("../node_modules/nuxt-site-config/dist/runtime/nuxt/component/SiteLink.vue")['default']
    'RobotMeta': typeof import("../node_modules/nuxt-simple-robots/dist/runtime/nuxt/components/RobotMeta")['default']
    'OgImage': typeof import("../node_modules/nuxt-og-image/dist/runtime/nuxt/components/OgImage/OgImage")['default']
    'OgImageScreenshot': typeof import("../node_modules/nuxt-og-image/dist/runtime/nuxt/components/OgImage/OgImageScreenshot")['default']
    'SchemaOrgDebug': typeof import("@unhead/schema-org/vue")['SchemaOrgDebug']
    'SchemaOrgArticle': typeof import("@unhead/schema-org/vue")['SchemaOrgArticle']
    'SchemaOrgBreadcrumb': typeof import("@unhead/schema-org/vue")['SchemaOrgBreadcrumb']
    'SchemaOrgComment': typeof import("@unhead/schema-org/vue")['SchemaOrgComment']
    'SchemaOrgEvent': typeof import("@unhead/schema-org/vue")['SchemaOrgEvent']
    'SchemaOrgFoodEstablishment': typeof import("@unhead/schema-org/vue")['SchemaOrgFoodEstablishment']
    'SchemaOrgHowTo': typeof import("@unhead/schema-org/vue")['SchemaOrgHowTo']
    'SchemaOrgImage': typeof import("@unhead/schema-org/vue")['SchemaOrgImage']
    'SchemaOrgJobPosting': typeof import("@unhead/schema-org/vue")['SchemaOrgJobPosting']
    'SchemaOrgLocalBusiness': typeof import("@unhead/schema-org/vue")['SchemaOrgLocalBusiness']
    'SchemaOrgOrganization': typeof import("@unhead/schema-org/vue")['SchemaOrgOrganization']
    'SchemaOrgPerson': typeof import("@unhead/schema-org/vue")['SchemaOrgPerson']
    'SchemaOrgProduct': typeof import("@unhead/schema-org/vue")['SchemaOrgProduct']
    'SchemaOrgQuestion': typeof import("@unhead/schema-org/vue")['SchemaOrgQuestion']
    'SchemaOrgRecipe': typeof import("@unhead/schema-org/vue")['SchemaOrgRecipe']
    'SchemaOrgReview': typeof import("@unhead/schema-org/vue")['SchemaOrgReview']
    'SchemaOrgVideo': typeof import("@unhead/schema-org/vue")['SchemaOrgVideo']
    'SchemaOrgWebPage': typeof import("@unhead/schema-org/vue")['SchemaOrgWebPage']
    'SchemaOrgWebSite': typeof import("@unhead/schema-org/vue")['SchemaOrgWebSite']
    'SchemaOrgMovie': typeof import("@unhead/schema-org/vue")['SchemaOrgMovie']
    'SchemaOrgCourse': typeof import("@unhead/schema-org/vue")['SchemaOrgCourse']
    'SchemaOrgItemList': typeof import("@unhead/schema-org/vue")['SchemaOrgItemList']
    'SchemaOrgBook': typeof import("@unhead/schema-org/vue")['SchemaOrgBook']
    'SchemaOrgSoftwareApp': typeof import("@unhead/schema-org/vue")['SchemaOrgSoftwareApp']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyContainer': typeof import("../components/global/Container.vue")['default']
    'LazySection': typeof import("../components/global/Section.vue")['default']
    'LazyAppFooter': typeof import("../components/app/Footer/Footer.vue")['default']
    'LazyAppHeader': typeof import("../components/app/Header/Header.vue")['default']
    'LazyAppHeaderHeaderDesktopLocale': typeof import("../components/app/Header/HeaderDesktop/HeaderDesktopLocale.vue")['default']
    'LazyAppHeaderHeaderDesktop': typeof import("../components/app/Header/HeaderDesktop/index.vue")['default']
    'LazyAppHeaderHeaderMenuLink': typeof import("../components/app/Header/HeaderMenuLink/index.vue")['default']
    'LazyAppHeaderHeaderMobileBurger': typeof import("../components/app/Header/HeaderMobile/HeaderMobileBurger.vue")['default']
    'LazyAppHeaderHeaderMobileLocale': typeof import("../components/app/Header/HeaderMobile/HeaderMobileLocale.vue")['default']
    'LazyAppHeaderHeaderMobileMenu': typeof import("../components/app/Header/HeaderMobile/HeaderMobileMenu.vue")['default']
    'LazyAppHeaderHeaderMobile': typeof import("../components/app/Header/HeaderMobile/index.vue")['default']
    'LazyIconsIconDownloadAppStore': typeof import("../components/icons/IconDownloadAppStore.vue")['default']
    'LazyIconsIconDownloadGooglePlay': typeof import("../components/icons/IconDownloadGooglePlay.vue")['default']
    'LazyIconsIconDownloadMacOs': typeof import("../components/icons/IconDownloadMacOs.vue")['default']
    'LazyIconsIconDownloadWindows': typeof import("../components/icons/IconDownloadWindows.vue")['default']
    'LazyIconsIconEarth': typeof import("../components/icons/IconEarth.vue")['default']
    'LazyIconsIconWrap': typeof import("../components/icons/IconWrap.vue")['default']
    'LazyPagesMainBenefits': typeof import("../components/pages/main/Benefits.vue")['default']
    'LazyPagesMainFaq': typeof import("../components/pages/main/Faq.vue")['default']
    'LazyPagesMainFaqItem': typeof import("../components/pages/main/Faq/FaqItem.vue")['default']
    'LazyPagesMainFcp': typeof import("../components/pages/main/Fcp.vue")['default']
    'LazyPagesMainGlobalNetwork': typeof import("../components/pages/main/GlobalNetwork.vue")['default']
    'LazyPagesMainGlobalNetworkCard': typeof import("../components/pages/main/GlobalNetwork/GlobalNetworkCard.vue")['default']
    'LazyPagesMainNoLogs': typeof import("../components/pages/main/NoLogs.vue")['default']
    'LazyPagesMainNoLogsCard': typeof import("../components/pages/main/NoLogs/NoLogsCard.vue")['default']
    'LazyPagesMainServers': typeof import("../components/pages/main/Servers.vue")['default']
    'LazyPagesMainServersCard': typeof import("../components/pages/main/Servers/ServersCard.vue")['default']
    'LazyPagesMainSupport': typeof import("../components/pages/main/Support.vue")['default']
    'LazyPagesMainSupportDonateCalc': typeof import("../components/pages/main/Support/DonateCalc.vue")['default']
    'LazySectionsBenefitsOfServers': typeof import("../components/sections/BenefitsOfServers.vue")['default']
    'LazySectionsBenefitsOfServersCard': typeof import("../components/sections/BenefitsOfServers/BenefitsOfServersCard.vue")['default']
    'LazySectionsConnectAndPrivate': typeof import("../components/sections/ConnectAndPrivate.vue")['default']
    'LazySectionsConnectAndPrivateCard': typeof import("../components/sections/ConnectAndPrivate/ConnectAndPrivateCard.vue")['default']
    'LazySectionsFirstContentfulPaint': typeof import("../components/sections/FirstContentfulPaint.vue")['default']
    'LazySectionsHowToSetUp': typeof import("../components/sections/HowToSetUp.vue")['default']
    'LazySectionsHowToSetUpCard': typeof import("../components/sections/HowToSetUp/SetUpCard.vue")['default']
    'LazySectionsPlatformsListPlatformItem': typeof import("../components/sections/PlatformsList/PlatformItem.vue")['default']
    'LazySectionsPlatformsList': typeof import("../components/sections/PlatformsList/PlatformsList.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtImg': typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-img")['default']
    'LazyNuxtPicture': typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-picture")['default']
    'LazyNuxtLinkLocale': typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
    'LazySwitchLocalePathLink': typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
    'LazySiteLink': typeof import("../node_modules/nuxt-site-config/dist/runtime/nuxt/component/SiteLink.vue")['default']
    'LazyRobotMeta': typeof import("../node_modules/nuxt-simple-robots/dist/runtime/nuxt/components/RobotMeta")['default']
    'LazyOgImage': typeof import("../node_modules/nuxt-og-image/dist/runtime/nuxt/components/OgImage/OgImage")['default']
    'LazyOgImageScreenshot': typeof import("../node_modules/nuxt-og-image/dist/runtime/nuxt/components/OgImage/OgImageScreenshot")['default']
    'LazySchemaOrgDebug': typeof import("@unhead/schema-org/vue")['SchemaOrgDebug']
    'LazySchemaOrgArticle': typeof import("@unhead/schema-org/vue")['SchemaOrgArticle']
    'LazySchemaOrgBreadcrumb': typeof import("@unhead/schema-org/vue")['SchemaOrgBreadcrumb']
    'LazySchemaOrgComment': typeof import("@unhead/schema-org/vue")['SchemaOrgComment']
    'LazySchemaOrgEvent': typeof import("@unhead/schema-org/vue")['SchemaOrgEvent']
    'LazySchemaOrgFoodEstablishment': typeof import("@unhead/schema-org/vue")['SchemaOrgFoodEstablishment']
    'LazySchemaOrgHowTo': typeof import("@unhead/schema-org/vue")['SchemaOrgHowTo']
    'LazySchemaOrgImage': typeof import("@unhead/schema-org/vue")['SchemaOrgImage']
    'LazySchemaOrgJobPosting': typeof import("@unhead/schema-org/vue")['SchemaOrgJobPosting']
    'LazySchemaOrgLocalBusiness': typeof import("@unhead/schema-org/vue")['SchemaOrgLocalBusiness']
    'LazySchemaOrgOrganization': typeof import("@unhead/schema-org/vue")['SchemaOrgOrganization']
    'LazySchemaOrgPerson': typeof import("@unhead/schema-org/vue")['SchemaOrgPerson']
    'LazySchemaOrgProduct': typeof import("@unhead/schema-org/vue")['SchemaOrgProduct']
    'LazySchemaOrgQuestion': typeof import("@unhead/schema-org/vue")['SchemaOrgQuestion']
    'LazySchemaOrgRecipe': typeof import("@unhead/schema-org/vue")['SchemaOrgRecipe']
    'LazySchemaOrgReview': typeof import("@unhead/schema-org/vue")['SchemaOrgReview']
    'LazySchemaOrgVideo': typeof import("@unhead/schema-org/vue")['SchemaOrgVideo']
    'LazySchemaOrgWebPage': typeof import("@unhead/schema-org/vue")['SchemaOrgWebPage']
    'LazySchemaOrgWebSite': typeof import("@unhead/schema-org/vue")['SchemaOrgWebSite']
    'LazySchemaOrgMovie': typeof import("@unhead/schema-org/vue")['SchemaOrgMovie']
    'LazySchemaOrgCourse': typeof import("@unhead/schema-org/vue")['SchemaOrgCourse']
    'LazySchemaOrgItemList': typeof import("@unhead/schema-org/vue")['SchemaOrgItemList']
    'LazySchemaOrgBook': typeof import("@unhead/schema-org/vue")['SchemaOrgBook']
    'LazySchemaOrgSoftwareApp': typeof import("@unhead/schema-org/vue")['SchemaOrgSoftwareApp']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module '@vue/runtime-core' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module '@vue/runtime-dom' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const Container: typeof import("../components/global/Container.vue")['default']
export const Section: typeof import("../components/global/Section.vue")['default']
export const AppFooter: typeof import("../components/app/Footer/Footer.vue")['default']
export const AppHeader: typeof import("../components/app/Header/Header.vue")['default']
export const AppHeaderHeaderDesktopLocale: typeof import("../components/app/Header/HeaderDesktop/HeaderDesktopLocale.vue")['default']
export const AppHeaderHeaderDesktop: typeof import("../components/app/Header/HeaderDesktop/index.vue")['default']
export const AppHeaderHeaderMenuLink: typeof import("../components/app/Header/HeaderMenuLink/index.vue")['default']
export const AppHeaderHeaderMobileBurger: typeof import("../components/app/Header/HeaderMobile/HeaderMobileBurger.vue")['default']
export const AppHeaderHeaderMobileLocale: typeof import("../components/app/Header/HeaderMobile/HeaderMobileLocale.vue")['default']
export const AppHeaderHeaderMobileMenu: typeof import("../components/app/Header/HeaderMobile/HeaderMobileMenu.vue")['default']
export const AppHeaderHeaderMobile: typeof import("../components/app/Header/HeaderMobile/index.vue")['default']
export const IconsIconDownloadAppStore: typeof import("../components/icons/IconDownloadAppStore.vue")['default']
export const IconsIconDownloadGooglePlay: typeof import("../components/icons/IconDownloadGooglePlay.vue")['default']
export const IconsIconDownloadMacOs: typeof import("../components/icons/IconDownloadMacOs.vue")['default']
export const IconsIconDownloadWindows: typeof import("../components/icons/IconDownloadWindows.vue")['default']
export const IconsIconEarth: typeof import("../components/icons/IconEarth.vue")['default']
export const IconsIconWrap: typeof import("../components/icons/IconWrap.vue")['default']
export const PagesMainBenefits: typeof import("../components/pages/main/Benefits.vue")['default']
export const PagesMainFaq: typeof import("../components/pages/main/Faq.vue")['default']
export const PagesMainFaqItem: typeof import("../components/pages/main/Faq/FaqItem.vue")['default']
export const PagesMainFcp: typeof import("../components/pages/main/Fcp.vue")['default']
export const PagesMainGlobalNetwork: typeof import("../components/pages/main/GlobalNetwork.vue")['default']
export const PagesMainGlobalNetworkCard: typeof import("../components/pages/main/GlobalNetwork/GlobalNetworkCard.vue")['default']
export const PagesMainNoLogs: typeof import("../components/pages/main/NoLogs.vue")['default']
export const PagesMainNoLogsCard: typeof import("../components/pages/main/NoLogs/NoLogsCard.vue")['default']
export const PagesMainServers: typeof import("../components/pages/main/Servers.vue")['default']
export const PagesMainServersCard: typeof import("../components/pages/main/Servers/ServersCard.vue")['default']
export const PagesMainSupport: typeof import("../components/pages/main/Support.vue")['default']
export const PagesMainSupportDonateCalc: typeof import("../components/pages/main/Support/DonateCalc.vue")['default']
export const SectionsBenefitsOfServers: typeof import("../components/sections/BenefitsOfServers.vue")['default']
export const SectionsBenefitsOfServersCard: typeof import("../components/sections/BenefitsOfServers/BenefitsOfServersCard.vue")['default']
export const SectionsConnectAndPrivate: typeof import("../components/sections/ConnectAndPrivate.vue")['default']
export const SectionsConnectAndPrivateCard: typeof import("../components/sections/ConnectAndPrivate/ConnectAndPrivateCard.vue")['default']
export const SectionsFirstContentfulPaint: typeof import("../components/sections/FirstContentfulPaint.vue")['default']
export const SectionsHowToSetUp: typeof import("../components/sections/HowToSetUp.vue")['default']
export const SectionsHowToSetUpCard: typeof import("../components/sections/HowToSetUp/SetUpCard.vue")['default']
export const SectionsPlatformsListPlatformItem: typeof import("../components/sections/PlatformsList/PlatformItem.vue")['default']
export const SectionsPlatformsList: typeof import("../components/sections/PlatformsList/PlatformsList.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtImg: typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-img")['default']
export const NuxtPicture: typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-picture")['default']
export const NuxtLinkLocale: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
export const SwitchLocalePathLink: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
export const SiteLink: typeof import("../node_modules/nuxt-site-config/dist/runtime/nuxt/component/SiteLink.vue")['default']
export const RobotMeta: typeof import("../node_modules/nuxt-simple-robots/dist/runtime/nuxt/components/RobotMeta")['default']
export const OgImage: typeof import("../node_modules/nuxt-og-image/dist/runtime/nuxt/components/OgImage/OgImage")['default']
export const OgImageScreenshot: typeof import("../node_modules/nuxt-og-image/dist/runtime/nuxt/components/OgImage/OgImageScreenshot")['default']
export const SchemaOrgDebug: typeof import("@unhead/schema-org/vue")['SchemaOrgDebug']
export const SchemaOrgArticle: typeof import("@unhead/schema-org/vue")['SchemaOrgArticle']
export const SchemaOrgBreadcrumb: typeof import("@unhead/schema-org/vue")['SchemaOrgBreadcrumb']
export const SchemaOrgComment: typeof import("@unhead/schema-org/vue")['SchemaOrgComment']
export const SchemaOrgEvent: typeof import("@unhead/schema-org/vue")['SchemaOrgEvent']
export const SchemaOrgFoodEstablishment: typeof import("@unhead/schema-org/vue")['SchemaOrgFoodEstablishment']
export const SchemaOrgHowTo: typeof import("@unhead/schema-org/vue")['SchemaOrgHowTo']
export const SchemaOrgImage: typeof import("@unhead/schema-org/vue")['SchemaOrgImage']
export const SchemaOrgJobPosting: typeof import("@unhead/schema-org/vue")['SchemaOrgJobPosting']
export const SchemaOrgLocalBusiness: typeof import("@unhead/schema-org/vue")['SchemaOrgLocalBusiness']
export const SchemaOrgOrganization: typeof import("@unhead/schema-org/vue")['SchemaOrgOrganization']
export const SchemaOrgPerson: typeof import("@unhead/schema-org/vue")['SchemaOrgPerson']
export const SchemaOrgProduct: typeof import("@unhead/schema-org/vue")['SchemaOrgProduct']
export const SchemaOrgQuestion: typeof import("@unhead/schema-org/vue")['SchemaOrgQuestion']
export const SchemaOrgRecipe: typeof import("@unhead/schema-org/vue")['SchemaOrgRecipe']
export const SchemaOrgReview: typeof import("@unhead/schema-org/vue")['SchemaOrgReview']
export const SchemaOrgVideo: typeof import("@unhead/schema-org/vue")['SchemaOrgVideo']
export const SchemaOrgWebPage: typeof import("@unhead/schema-org/vue")['SchemaOrgWebPage']
export const SchemaOrgWebSite: typeof import("@unhead/schema-org/vue")['SchemaOrgWebSite']
export const SchemaOrgMovie: typeof import("@unhead/schema-org/vue")['SchemaOrgMovie']
export const SchemaOrgCourse: typeof import("@unhead/schema-org/vue")['SchemaOrgCourse']
export const SchemaOrgItemList: typeof import("@unhead/schema-org/vue")['SchemaOrgItemList']
export const SchemaOrgBook: typeof import("@unhead/schema-org/vue")['SchemaOrgBook']
export const SchemaOrgSoftwareApp: typeof import("@unhead/schema-org/vue")['SchemaOrgSoftwareApp']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyContainer: typeof import("../components/global/Container.vue")['default']
export const LazySection: typeof import("../components/global/Section.vue")['default']
export const LazyAppFooter: typeof import("../components/app/Footer/Footer.vue")['default']
export const LazyAppHeader: typeof import("../components/app/Header/Header.vue")['default']
export const LazyAppHeaderHeaderDesktopLocale: typeof import("../components/app/Header/HeaderDesktop/HeaderDesktopLocale.vue")['default']
export const LazyAppHeaderHeaderDesktop: typeof import("../components/app/Header/HeaderDesktop/index.vue")['default']
export const LazyAppHeaderHeaderMenuLink: typeof import("../components/app/Header/HeaderMenuLink/index.vue")['default']
export const LazyAppHeaderHeaderMobileBurger: typeof import("../components/app/Header/HeaderMobile/HeaderMobileBurger.vue")['default']
export const LazyAppHeaderHeaderMobileLocale: typeof import("../components/app/Header/HeaderMobile/HeaderMobileLocale.vue")['default']
export const LazyAppHeaderHeaderMobileMenu: typeof import("../components/app/Header/HeaderMobile/HeaderMobileMenu.vue")['default']
export const LazyAppHeaderHeaderMobile: typeof import("../components/app/Header/HeaderMobile/index.vue")['default']
export const LazyIconsIconDownloadAppStore: typeof import("../components/icons/IconDownloadAppStore.vue")['default']
export const LazyIconsIconDownloadGooglePlay: typeof import("../components/icons/IconDownloadGooglePlay.vue")['default']
export const LazyIconsIconDownloadMacOs: typeof import("../components/icons/IconDownloadMacOs.vue")['default']
export const LazyIconsIconDownloadWindows: typeof import("../components/icons/IconDownloadWindows.vue")['default']
export const LazyIconsIconEarth: typeof import("../components/icons/IconEarth.vue")['default']
export const LazyIconsIconWrap: typeof import("../components/icons/IconWrap.vue")['default']
export const LazyPagesMainBenefits: typeof import("../components/pages/main/Benefits.vue")['default']
export const LazyPagesMainFaq: typeof import("../components/pages/main/Faq.vue")['default']
export const LazyPagesMainFaqItem: typeof import("../components/pages/main/Faq/FaqItem.vue")['default']
export const LazyPagesMainFcp: typeof import("../components/pages/main/Fcp.vue")['default']
export const LazyPagesMainGlobalNetwork: typeof import("../components/pages/main/GlobalNetwork.vue")['default']
export const LazyPagesMainGlobalNetworkCard: typeof import("../components/pages/main/GlobalNetwork/GlobalNetworkCard.vue")['default']
export const LazyPagesMainNoLogs: typeof import("../components/pages/main/NoLogs.vue")['default']
export const LazyPagesMainNoLogsCard: typeof import("../components/pages/main/NoLogs/NoLogsCard.vue")['default']
export const LazyPagesMainServers: typeof import("../components/pages/main/Servers.vue")['default']
export const LazyPagesMainServersCard: typeof import("../components/pages/main/Servers/ServersCard.vue")['default']
export const LazyPagesMainSupport: typeof import("../components/pages/main/Support.vue")['default']
export const LazyPagesMainSupportDonateCalc: typeof import("../components/pages/main/Support/DonateCalc.vue")['default']
export const LazySectionsBenefitsOfServers: typeof import("../components/sections/BenefitsOfServers.vue")['default']
export const LazySectionsBenefitsOfServersCard: typeof import("../components/sections/BenefitsOfServers/BenefitsOfServersCard.vue")['default']
export const LazySectionsConnectAndPrivate: typeof import("../components/sections/ConnectAndPrivate.vue")['default']
export const LazySectionsConnectAndPrivateCard: typeof import("../components/sections/ConnectAndPrivate/ConnectAndPrivateCard.vue")['default']
export const LazySectionsFirstContentfulPaint: typeof import("../components/sections/FirstContentfulPaint.vue")['default']
export const LazySectionsHowToSetUp: typeof import("../components/sections/HowToSetUp.vue")['default']
export const LazySectionsHowToSetUpCard: typeof import("../components/sections/HowToSetUp/SetUpCard.vue")['default']
export const LazySectionsPlatformsListPlatformItem: typeof import("../components/sections/PlatformsList/PlatformItem.vue")['default']
export const LazySectionsPlatformsList: typeof import("../components/sections/PlatformsList/PlatformsList.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtImg: typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-img")['default']
export const LazyNuxtPicture: typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-picture")['default']
export const LazyNuxtLinkLocale: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
export const LazySwitchLocalePathLink: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
export const LazySiteLink: typeof import("../node_modules/nuxt-site-config/dist/runtime/nuxt/component/SiteLink.vue")['default']
export const LazyRobotMeta: typeof import("../node_modules/nuxt-simple-robots/dist/runtime/nuxt/components/RobotMeta")['default']
export const LazyOgImage: typeof import("../node_modules/nuxt-og-image/dist/runtime/nuxt/components/OgImage/OgImage")['default']
export const LazyOgImageScreenshot: typeof import("../node_modules/nuxt-og-image/dist/runtime/nuxt/components/OgImage/OgImageScreenshot")['default']
export const LazySchemaOrgDebug: typeof import("@unhead/schema-org/vue")['SchemaOrgDebug']
export const LazySchemaOrgArticle: typeof import("@unhead/schema-org/vue")['SchemaOrgArticle']
export const LazySchemaOrgBreadcrumb: typeof import("@unhead/schema-org/vue")['SchemaOrgBreadcrumb']
export const LazySchemaOrgComment: typeof import("@unhead/schema-org/vue")['SchemaOrgComment']
export const LazySchemaOrgEvent: typeof import("@unhead/schema-org/vue")['SchemaOrgEvent']
export const LazySchemaOrgFoodEstablishment: typeof import("@unhead/schema-org/vue")['SchemaOrgFoodEstablishment']
export const LazySchemaOrgHowTo: typeof import("@unhead/schema-org/vue")['SchemaOrgHowTo']
export const LazySchemaOrgImage: typeof import("@unhead/schema-org/vue")['SchemaOrgImage']
export const LazySchemaOrgJobPosting: typeof import("@unhead/schema-org/vue")['SchemaOrgJobPosting']
export const LazySchemaOrgLocalBusiness: typeof import("@unhead/schema-org/vue")['SchemaOrgLocalBusiness']
export const LazySchemaOrgOrganization: typeof import("@unhead/schema-org/vue")['SchemaOrgOrganization']
export const LazySchemaOrgPerson: typeof import("@unhead/schema-org/vue")['SchemaOrgPerson']
export const LazySchemaOrgProduct: typeof import("@unhead/schema-org/vue")['SchemaOrgProduct']
export const LazySchemaOrgQuestion: typeof import("@unhead/schema-org/vue")['SchemaOrgQuestion']
export const LazySchemaOrgRecipe: typeof import("@unhead/schema-org/vue")['SchemaOrgRecipe']
export const LazySchemaOrgReview: typeof import("@unhead/schema-org/vue")['SchemaOrgReview']
export const LazySchemaOrgVideo: typeof import("@unhead/schema-org/vue")['SchemaOrgVideo']
export const LazySchemaOrgWebPage: typeof import("@unhead/schema-org/vue")['SchemaOrgWebPage']
export const LazySchemaOrgWebSite: typeof import("@unhead/schema-org/vue")['SchemaOrgWebSite']
export const LazySchemaOrgMovie: typeof import("@unhead/schema-org/vue")['SchemaOrgMovie']
export const LazySchemaOrgCourse: typeof import("@unhead/schema-org/vue")['SchemaOrgCourse']
export const LazySchemaOrgItemList: typeof import("@unhead/schema-org/vue")['SchemaOrgItemList']
export const LazySchemaOrgBook: typeof import("@unhead/schema-org/vue")['SchemaOrgBook']
export const LazySchemaOrgSoftwareApp: typeof import("@unhead/schema-org/vue")['SchemaOrgSoftwareApp']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
